### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by jeongjjw** [candymate/cs434-project#11]
각 worker 마다 port가 8000번인 서버를 열어서 한 host에서 가상 머신을 사용하지 않는 이상 2개 이상의 worker를 동시에 테스트하기 어려움 
https://www.baeldung.com/docker-test-containers를 이용해서 추가적인 테스트 환경 구축이 필요

**Comment by candymate** [comment]
이거 걍 worker에 port 설정으로 줄 수 있게 하면 안되려나. port를 따로 지정하지 않으면 기본 포트 (아마 8000?)로 작동할 수 있도록 해서. 그러면 가상환경 따로 구축 안해도 될듯? (디렉토리 구분만 할 수 있도록)

그리고 또 worker에 임의로 idx 지정할 수 있었으면 좋겠음. 뒤에 merge나 shuffling 테스트 할 때 필요할듯. (그래야 앞 단계 다 안 거치고 테스트 가능)

**Comment by jeongjjw** [comment]
@candymate
1. parameter로 받을 수 있도록 구현하는게 좋을 거 같음 
2. worker의 idx를 지정하는게 master에 도착해서 저장되어 있는 머신 순서를 말하는 뜻임 ?

**Comment by candymate** [comment]
@jeongjjw 

worker idx는 저장되어 있는 머신 순서. Connection이나 Sampling 단계에서 Master가 Worker에게 보내주는 연결 정보 (worker list)의 순서라고 생각해도 될듯.

**Comment by jeongjjw** [comment]
@candymate 
아 지금은 순서가 도착한 순서대로 구현되어 있는데, 그 값도 임의로 설정할 수 있으면 좋을 거 같다는 거지?

**Comment by jeongjjw** [comment]
@candymate 
지금도 테스트 구현은 Thread sleep 으로 worker가 켜지는 속도를 조절할 수는 있긴 함

**Comment by candymate** [comment]
@jeongjjw 
Worker 순서 유지할 수 있으면 괜찮을듯.

**Comment by jeongjjw** [comment]
https://github.com/candymate/cs434-project/pull/16 에서 해결
